# Data Analysis Techniques. Lab 3. Working with `numpy`, part 3

## 1. Selected arithmetic operations on a NumPy array

In [1]:
import numpy as np

In [2]:
# Functions taken from https://tobiasraabe.github.io/post/numpy-views-vs-copies/
# These functions make it easier to determine whether two NumPy arrays have a common base
# which means they share memory (or not)

def get_data_base(x):
    base = x
    while isinstance(base.base, np.ndarray):
        base = base.base
    return base

def arrays_share_data(x, y):
    return get_data_base(x) is get_data_base(y)

In [3]:
arr = np.arange(1,101).reshape((10,10))
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [4]:
# sum of all values in the array
print(arr.sum())
# lub
print(np.sum(arr))

5050
5050


In [5]:
# sum in each column (row indexing)
print(arr.sum(axis=0))
# and each rows (column indexing)
print(arr.sum(axis=1))

[460 470 480 490 500 510 520 530 540 550]
[ 55 155 255 355 455 555 655 755 855 955]


In [6]:
# cumulative sum
print(arr.cumsum())

[   1    3    6   10   15   21   28   36   45   55   66   78   91  105
  120  136  153  171  190  210  231  253  276  300  325  351  378  406
  435  465  496  528  561  595  630  666  703  741  780  820  861  903
  946  990 1035 1081 1128 1176 1225 1275 1326 1378 1431 1485 1540 1596
 1653 1711 1770 1830 1891 1953 2016 2080 2145 2211 2278 2346 2415 2485
 2556 2628 2701 2775 2850 2926 3003 3081 3160 3240 3321 3403 3486 3570
 3655 3741 3828 3916 4005 4095 4186 4278 4371 4465 4560 4656 4753 4851
 4950 5050]


In [7]:
# most of the functions can be run for a given axis
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 12  14  16  18  20  22  24  26  28  30]
 [ 33  36  39  42  45  48  51  54  57  60]
 [ 64  68  72  76  80  84  88  92  96 100]
 [105 110 115 120 125 130 135 140 145 150]
 [156 162 168 174 180 186 192 198 204 210]
 [217 224 231 238 245 252 259 266 273 280]
 [288 296 304 312 320 328 336 344 352 360]
 [369 378 387 396 405 414 423 432 441 450]
 [460 470 480 490 500 510 520 530 540 550]]
[[  1   3   6  10  15  21  28  36  45  55]
 [ 11  23  36  50  65  81  98 116 135 155]
 [ 21  43  66  90 115 141 168 196 225 255]
 [ 31  63  96 130 165 201 238 276 315 355]
 [ 41  83 126 170 215 261 308 356 405 455]
 [ 51 103 156 210 265 321 378 436 495 555]
 [ 61 123 186 250 315 381 448 516 585 655]
 [ 71 143 216 290 365 441 518 596 675 755]
 [ 81 163 246 330 415 501 588 676 765 855]
 [ 91 183 276 370 465 561 658 756 855 955]]


In [8]:
# For the purposes of a few examples, we will use a copy of the original array
arr_nan = arr.copy()

In [9]:
# Filtering an array returns a Boolean array—a map—of values that satisfy and do not satisfy the condition
divide_by_five_map = (arr_nan % 5 == 0)
divide_by_five_map

array([[False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True]])

In [10]:
# We'll also check from time to time whether we're working on a copy or a view
# Here we're dealing with what's known as “fancy slicing”—so it's a copy
arrays_share_data(arr_nan, divide_by_five_map)

False

In [11]:
# We can attach this panel to another panel (make sure the dimensions match!)
divide_by_five = arr_nan[divide_by_five_map]
divide_by_five

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [12]:
arrays_share_data(divide_by_five, arr_nan)

False

In [13]:
# We convert the values associated with the map indices to values such as “nan” (not a number)
arr_nan[divide_by_five_map] = np.nan

ValueError: cannot convert float NaN to integer

In [14]:
arr_nan

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [15]:
arr_nan.dtype

dtype('int64')

In [16]:
# It turns out that we can't do this for types like `int`
# Maybe for types like `float`
# After a failed insertion operation, we should check whether the array contains valid data
# If not, the copying operation should be performed again
arr_nan = arr_nan.astype(np.float64)
arr_nan

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [17]:
arr_nan[divide_by_five_map] = np.nan

In [18]:
# Let's perform the sum operation again
print(arr_nan.sum())

nan


In [19]:
print(arr_nan.sum(axis=0))
print(arr_nan.sum(axis=1))

[460. 470. 480. 490.  nan 510. 520. 530. 540.  nan]
[nan nan nan nan nan nan nan nan nan nan]


In [20]:
# If we want to treat nan values in a specific way, e.g., as 0 (zero), we have
# dedicated functions at our disposal—in this case, the sum function
print(np.nansum(arr_nan))
print(np.nansum(arr_nan, axis=0))
print(np.nansum(arr_nan, axis=1))

4000.0
[460. 470. 480. 490.   0. 510. 520. 530. 540.   0.]
[ 40. 120. 200. 280. 360. 440. 520. 600. 680. 760.]


In [21]:
# Multiplying array elements
# Not working? Why 0? This is due to an overflow of values for types supported by NumPy.
# Python's built-in int type can represent extremely large numbers (limited only by RAM), but  numpy
# is based on types known from the C language. Value overflow for types like int64 or float64 during multiplication can
# occur very quickly. In this case, 0 is returned without any warning—keep this in mind.
print(arr.prod())
print(arr.prod(axis=0))

0
[  478015854767451  1242688846823424  2394832584543399  4060162871525376
  6393838623046875  9585618768101376 13865696119905399 19511273389031424
 26853950884211451 36288000000000000]


In [22]:
# NumPy has a wide range of built-in functions for arithmetic, trigonometry, linear algebra, and more.
# We’ll cover linear algebra a bit later. Below are a few examples of other common operations.
print(arr.max(), arr.max(axis=0))

100 [ 91  92  93  94  95  96  97  98  99 100]


In [23]:
# We can also use operations of this type to filter an array
arr[(arr == arr.max(axis=0))]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [24]:
# Here, it’s also worth introducing a function like `where`, which, instead of returning values that meet a condition,
# can return the indices where those conditions are met. Below, we’ll see two arrays, since the array
# we’re filtering is two-dimensional. The first dimension is the row, and the second is the column.
# The `where` function takes up to three arguments: condition, x, y. If only the condition is provided, it returns the indices of the elements
# that satisfy that condition.

In [25]:
np.where(arr == arr.max(axis=0))

(array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [26]:
# What is the equivalent of the following?
np.asarray(arr == arr.max(axis=0)).nonzero()

(array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [27]:
# but we can also use it this way
# condition, value if the condition is met, value if the condition is not met
np.where(arr == arr.max(axis=0), arr, np.nan)

array([[ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

## 2. `np.random` module

The `np.random` module provides many functions that allow you to generate arrays of random values (more precisely, pseudo-random values, due to the way computers work) with specific properties, as well as to sample from existing arrays.

### 2.1 Selected examples of initializing arrays using `np.random`

To use the module, start by initializing the pseudorandom number generator.

In [28]:
rng = np.random.default_rng()

In [29]:
rng.random()

0.6721236328704715

In [30]:
rng.random((5,5))

array([[0.97937738, 0.99986847, 0.49119723, 0.08368017, 0.31983997],
       [0.50526296, 0.08196393, 0.13320852, 0.46375364, 0.45044827],
       [0.92523054, 0.77770867, 0.84606924, 0.75520575, 0.59795527],
       [0.26610728, 0.35790764, 0.11217402, 0.68689728, 0.58246273],
       [0.33015364, 0.24727091, 0.71353964, 0.89769734, 0.73107612]])

In [31]:
# The values returned are in the range [0.0, 1.0)

In [32]:
# We can sample pseudo-random values from distributions, such as the normal distribution
# Function signature: normal(loc=0.0, scale=1.0, size=None) (mean, standard deviation, size)
print(rng.normal())
print(rng.normal(size=(5,5)))

1.0360199624077806
[[-0.37500969 -0.58729385 -0.37180769 -0.77690387 -0.80453426]
 [-1.33142009  1.58351438 -0.01524738  0.22516601 -0.76261166]
 [-1.19927138  0.22485313  0.44536096 -0.74734178 -0.37264363]
 [ 1.2435071   0.93622854  1.12200128 -0.5337966  -2.51823924]
 [-0.49944633 -0.86372349  0.51145119 -0.90116882 -0.04082143]]


In [33]:
# or we can use the following function, where (mean=0.0, std=1.0)
rng.standard_normal(5)

array([ 0.01075894, -0.00824001,  1.06220998, -1.4089991 , -0.84257031])

In [34]:
# Generating integers from a range
rng.integers(low=1, high=100, size=10)

array([68, 96, 28,  8, 36, 44, 29, 87, 83, 36])

In [35]:
# choice - retrieves a random sample of data from an array
# signature: choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)
# The p parameter allows you to pass an array containing a probability distribution

In [36]:
# Note the output: a random line is returned
rng.choice(arr)

array([81, 82, 83, 84, 85, 86, 87, 88, 89, 90])

In [37]:
# By default, the selection is made with replacement (replace=True)
rng.choice(arr, size=20)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [38]:
rng.choice(arr, size=5, replace=False)

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90]])

In [39]:
# But what if we wanted to draw a single value from the array?
# We can use the functions we learned in the previous lab
rng.choice(arr.flat, size=10, replace=False)

array([85, 16, 22, 98, 53, 62, 78, 52, 50,  7])

In [40]:
# The array is “shuffled” in-place
rng.shuffle(arr)
arr

array([[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]])

In [41]:
# and by default axis=0, but we can change that
rng.shuffle(arr, axis=1)
arr

array([[ 84,  90,  88,  83,  81,  87,  89,  85,  86,  82],
       [ 34,  40,  38,  33,  31,  37,  39,  35,  36,  32],
       [ 64,  70,  68,  63,  61,  67,  69,  65,  66,  62],
       [ 54,  60,  58,  53,  51,  57,  59,  55,  56,  52],
       [ 24,  30,  28,  23,  21,  27,  29,  25,  26,  22],
       [ 44,  50,  48,  43,  41,  47,  49,  45,  46,  42],
       [ 74,  80,  78,  73,  71,  77,  79,  75,  76,  72],
       [ 94, 100,  98,  93,  91,  97,  99,  95,  96,  92],
       [ 14,  20,  18,  13,  11,  17,  19,  15,  16,  12],
       [  4,  10,   8,   3,   1,   7,   9,   5,   6,   2]])

In [42]:
# Generate a permutation from an array or by specifying an integer (works with most similar NumPy functions)
# Returns a permutation of integers within the specified range.
# The main difference between `shuffle` and `permutation` is that the former operates in-place
# while the latter returns a copy
rng.permutation(10)

array([5, 0, 7, 8, 9, 1, 6, 3, 2, 4])

In [43]:
rng.permutation(arr)

array([[  4,  10,   8,   3,   1,   7,   9,   5,   6,   2],
       [ 44,  50,  48,  43,  41,  47,  49,  45,  46,  42],
       [ 24,  30,  28,  23,  21,  27,  29,  25,  26,  22],
       [ 14,  20,  18,  13,  11,  17,  19,  15,  16,  12],
       [ 34,  40,  38,  33,  31,  37,  39,  35,  36,  32],
       [ 84,  90,  88,  83,  81,  87,  89,  85,  86,  82],
       [ 64,  70,  68,  63,  61,  67,  69,  65,  66,  62],
       [ 94, 100,  98,  93,  91,  97,  99,  95,  96,  92],
       [ 54,  60,  58,  53,  51,  57,  59,  55,  56,  52],
       [ 74,  80,  78,  73,  71,  77,  79,  75,  76,  72]])

## 2.2 Reading and writing arrays from and into a file

In [44]:
# saving array to a file
np.savetxt('arr.txt', arr)

In [45]:
# windows - reading a file using shell command
!type arr.txt
# unix or windows with WSL
# !cat arr.txt

arr.txt not found


In [46]:
# we can change the default format
np.savetxt('arr.txt', arr, fmt='%.1f')

In [47]:
!type arr.txt

arr.txt not found


In [48]:
# reading data from a file (this function has numerous parameters which may change the way the data are being loaded)
arr_from_file = np.loadtxt('arr.txt')

In [49]:
print(arr_from_file, arr_from_file.dtype)

[[ 84.  90.  88.  83.  81.  87.  89.  85.  86.  82.]
 [ 34.  40.  38.  33.  31.  37.  39.  35.  36.  32.]
 [ 64.  70.  68.  63.  61.  67.  69.  65.  66.  62.]
 [ 54.  60.  58.  53.  51.  57.  59.  55.  56.  52.]
 [ 24.  30.  28.  23.  21.  27.  29.  25.  26.  22.]
 [ 44.  50.  48.  43.  41.  47.  49.  45.  46.  42.]
 [ 74.  80.  78.  73.  71.  77.  79.  75.  76.  72.]
 [ 94. 100.  98.  93.  91.  97.  99.  95.  96.  92.]
 [ 14.  20.  18.  13.  11.  17.  19.  15.  16.  12.]
 [  4.  10.   8.   3.   1.   7.   9.   5.   6.   2.]] float64


In [50]:
# This format is, of course, convenient for humans, and data is often provided in this form
# however, it is not the most efficient method available.
# Here I will show just one of the possibilities, but to expand your knowledge, you might want to look into the data formats
# used in Big Data applications.
np.save('arr_pickle', arr)

## Tasks


1. Create an array named `a_small_one` with dimensions 8x8 and values 1, 2, ..., 64.




In [51]:
import numpy as np

# Task 1: 8x8 with 1..64
a_small_one = np.arange(1, 65).reshape(8, 8)
print(a_small_one)



[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]



2. For the array `a_small_one`, calculate:
   * the sum for each column,
   * the cumulative sum for each row,
   * the average value for each row,




In [52]:
import numpy as np

# Run task 1 first, or rebuild the array here:
a_small_one = np.arange(1, 65).reshape(8, 8)

# Sum of each column
col_sums = []
for j in range(8):
    col_sums.append(a_small_one[:, j].sum())
print("Sum per column:", np.array(col_sums))

# Cumulative sum inside each row
for i in range(8):
    row = a_small_one[i, :]
    csum = np.cumsum(row)
    print("Row", i, "cumsum:", csum)

# Average of each row
row_means = []
for i in range(8):
    row_means.append(a_small_one[i, :].mean())
print("Mean per row:", np.array(row_means))



Sum per column: [232 240 248 256 264 272 280 288]
Row 0 cumsum: [ 1  3  6 10 15 21 28 36]
Row 1 cumsum: [  9  19  30  42  55  69  84 100]
Row 2 cumsum: [ 17  35  54  74  95 117 140 164]
Row 3 cumsum: [ 25  51  78 106 135 165 196 228]
Row 4 cumsum: [ 33  67 102 138 175 213 252 292]
Row 5 cumsum: [ 41  83 126 170 215 261 308 356]
Row 6 cumsum: [ 49  99 150 202 255 309 364 420]
Row 7 cumsum: [ 57 115 174 234 295 357 420 484]
Mean per row: [ 4.5 12.5 20.5 28.5 36.5 44.5 52.5 60.5]



3. Return a subarray from the array `a_small_one` containing even-numbered elements (do not overwrite this variable).




In [53]:
import numpy as np

a_small_one = np.arange(1, 65).reshape(8, 8)

# Task 3: only the even numbers, as a new array (do not change a_small_one)
picked = []
for value in a_small_one.ravel():
    if value % 2 == 0:
        picked.append(value)
evens = np.array(picked)
print(evens)



[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]



4. Save the array `a_small_one` to a variable named `no_even_small_one`, replacing even values with a value such as `nan`.




In [54]:
import numpy as np

a_small_one = np.arange(1, 65).reshape(8, 8)

# Task 4: copy as float, replace even entries with nan
no_even_small_one = a_small_one.astype(float)
for r in range(8):
    for c in range(8):
        if a_small_one[r, c] % 2 == 0:
            no_even_small_one[r, c] = np.nan
print(no_even_small_one)



[[ 1. nan  3. nan  5. nan  7. nan]
 [ 9. nan 11. nan 13. nan 15. nan]
 [17. nan 19. nan 21. nan 23. nan]
 [25. nan 27. nan 29. nan 31. nan]
 [33. nan 35. nan 37. nan 39. nan]
 [41. nan 43. nan 45. nan 47. nan]
 [49. nan 51. nan 53. nan 55. nan]
 [57. nan 59. nan 61. nan 63. nan]]



5. For the array `no_even_small_one`, calculate the following using functions that handle `nan` values (these functions usually have the prefix `nan`):
   * the sum for each row,
   * the average for each column,
   * the smallest value in the entire array,




In [55]:
import numpy as np

# Rebuild from previous steps if you restarted the kernel
a_small_one = np.arange(1, 65).reshape(8, 8)
no_even_small_one = a_small_one.astype(float)
for r in range(8):
    for c in range(8):
        if a_small_one[r, c] % 2 == 0:
            no_even_small_one[r, c] = np.nan

# Task 5: ignore NaNs using nan* functions
for i in range(8):
    print("Row", i, "nansum:", np.nansum(no_even_small_one[i, :]))

for j in range(8):
    print("Col", j, "nanmean:", np.nanmean(no_even_small_one[:, j]))

print("Smallest value ignoring nan:", np.nanmin(no_even_small_one))



Row 0 nansum: 16.0
Row 1 nansum: 48.0
Row 2 nansum: 80.0
Row 3 nansum: 112.0
Row 4 nansum: 144.0
Row 5 nansum: 176.0
Row 6 nansum: 208.0
Row 7 nansum: 240.0
Col 0 nanmean: 29.0
Col 1 nanmean: nan
Col 2 nanmean: 31.0
Col 3 nanmean: nan
Col 4 nanmean: 33.0
Col 5 nanmean: nan
Col 6 nanmean: 35.0
Col 7 nanmean: nan
Smallest value ignoring nan: 1.0


/tmp/ipykernel_13736/3766894195.py:16: RuntimeWarning: Mean of empty slice
  print("Col", j, "nanmean:", np.nanmean(no_even_small_one[:, j]))



6. Insert the following into the `no_even_small_one` array using the `np.where` function:

   * the value 1 for each `np.nan` value (see the built-in `np.isnan()` function)
   * even numbers, which we previously replaced with `nan` values (now 1 if the first step is completed), so we restore the array to its original state from the `a_small_one` array—for the condition, insert the value from `a_small_one` or `no_even_small_one`




In [56]:
import numpy as np

a_small_one = np.arange(1, 65).reshape(8, 8)
no_even_small_one = a_small_one.astype(float)
for r in range(8):
    for c in range(8):
        if a_small_one[r, c] % 2 == 0:
            no_even_small_one[r, c] = np.nan

# Task 6: put 1 where NaN, then restore real evens from a_small_one
step = np.where(np.isnan(no_even_small_one), 1.0, no_even_small_one)
mask_even = a_small_one % 2 == 0
restored = np.where(mask_even, a_small_one.astype(float), step)
print(restored)
print("Matches original:", np.allclose(restored, a_small_one.astype(float)))



[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30. 31. 32.]
 [33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63. 64.]]
Matches original: True



7. Create an array named `normal_100` with dimensions 100x100 by sampling values from a standard normal distribution using a `np.random` module.




In [57]:
import numpy as np

# Task 7: 100x100 standard normal draws
rng = np.random.default_rng(seed=0)
normal_100 = rng.standard_normal((100, 100))
print(normal_100.shape)



(100, 100)



8. For the `normal_100` array, calculate:
   * the mean value in each row and column (separately),
   * calculate the average absolute difference for the values in the previous point relative to the value 0 (this is the expected value given our assumptions about the normal distribution) — separately for the column averages and the row averages; keep in mind that operations on a NumPy array are performed in broadcast mode.




In [58]:
import numpy as np

rng = np.random.default_rng(seed=0)
normal_100 = rng.standard_normal((100, 100))

# Mean of each row
row_means = []
for i in range(100):
    row_means.append(normal_100[i, :].mean())

# Mean of each column
col_means = []
for j in range(100):
    col_means.append(normal_100[:, j].mean())

row_means = np.array(row_means)
col_means = np.array(col_means)

# Average absolute distance of those means from 0
sum_row = 0.0
for v in row_means:
    sum_row += abs(v - 0.0)
avg_abs_row = sum_row / len(row_means)

sum_col = 0.0
for v in col_means:
    sum_col += abs(v - 0.0)
avg_abs_col = sum_col / len(col_means)

print("Avg |row means| from 0:", avg_abs_row)
print("Avg |col means| from 0:", avg_abs_col)



Avg |row means| from 0: 0.08301169146163577
Avg |col means| from 0: 0.07453437571562602



9. Create a 1000x1000 array by filling it with random values from a standard normal distribution, and then, using examples from previous labs (the `timeit` module), compare the execution times for this array:
    * writing to a text file vs. writing to a file in pickle format vs. writing to a compressed file (the `savez_compressed` function in the NumPy library documentation)
    * reading arrays back from the three files mentioned above.



In [59]:
import numpy as np
import pickle
import os
import tempfile
from timeit import timeit

# Task 9: time saving/loading big array three ways
rng = np.random.default_rng(1)
big = rng.standard_normal((1000, 1000))
folder = tempfile.mkdtemp()
path_txt = os.path.join(folder, "arr.txt")
path_pkl = os.path.join(folder, "arr.pkl")
path_npz = os.path.join(folder, "arr.npz")


def write_txt():
    np.savetxt(path_txt, big)


def read_txt():
    return np.loadtxt(path_txt)


def write_pkl():
    with open(path_pkl, "wb") as f:
        pickle.dump(big, f)


def read_pkl():
    with open(path_pkl, "rb") as f:
        return pickle.load(f)


def write_npz():
    np.savez_compressed(path_npz, data=big)


def read_npz():
    loaded = np.load(path_npz)
    return loaded["data"]


runs = 2
print("write txt:", timeit(write_txt, number=runs))
print("write pkl:", timeit(write_pkl, number=runs))
print("write npz:", timeit(write_npz, number=runs))
print("read txt:", timeit(read_txt, number=runs))
print("read pkl:", timeit(read_pkl, number=runs))
print("read npz:", timeit(read_npz, number=runs))



write txt: 2.1078467600000295
write pkl: 0.06554759600021498


write npz: 0.6645385640003951


read txt: 0.7616072229993733
read pkl: 0.00605010300023423
read npz: 0.09309667600064131
