# Data Analysis Techniques. Lab 1. Working with `numpy`, part 1

# 1. Short introduction

The `NumPy` is a library dedicated to numerical computations, implemented primarily in C (yes, that’s right - we’re working on the CPython implementation). Its main data object is a multidimensional (`ndarray`) that supports multiple data types but is homogeneous. This library also provides many mathematical methods, e.g., in the fields of linear algebra, statistics, and pseudorandom number generators.

> Official documentation page for version 2.4: https://numpy.org/doc/2.4/index.html

Its undoubted advantage is the optimization of methods for vector computations (across entire “rows, columns, or matrices”), so it is often used as a component of many other libraries (e.g., pandas, Dask, scikit-learn, and others).

## 1.1 `numpy` installation

One can run shell commands directly within a Jupyter cell, but these must be preceded by an exclamation mark.

In [1]:
!pip install numpy

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detai

In [2]:
# importing numpy into context
import numpy as np

In [3]:
np.__version__

'2.4.4'

# 2. `numpy.ndarray` data type

 ## 2.1 Array initialization

> **Docs**: https://numpy.org/doc/2.4/reference/routines.array-creation.html

In [4]:
# The built-in `dir` function displays a list of properties and methods that can be
# called for a given object type—as you can see, an ndarray (n-dimensional array) has
# quite a few of them, but this way of displaying them can be considered a fun fact or a quick way to jog your memory about the name of one of them
# A better place to start is the official documentation.
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [5]:
# array may be initialized in many ways
# using casting (changing type for an object) for example
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
arr, type(arr)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [6]:
# is casting possible also for mulidimensional Python lists?
nested_list = [[i*j for j in range(1, 6)] for i in range(1, 6)]
display(nested_list) 
len(nested_list)

[[1, 2, 3, 4, 5],
 [2, 4, 6, 8, 10],
 [3, 6, 9, 12, 15],
 [4, 8, 12, 16, 20],
 [5, 10, 15, 20, 25]]

5

In [7]:
arr_nested = np.array(nested_list)
arr_nested

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

As we see - it is.

In [8]:
# but there are certain rules and limitations
# this two dimensional list contains list of different lengths
nested_asym_list = [[x for x in range(1, y)] for y in range(1, 6)]
nested_asym_list

[[], [1], [1, 2], [1, 2, 3], [1, 2, 3, 4]]

In [9]:
# this won't work!
arr_nested_asym = np.array(nested_asym_list)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [10]:
# casting from a builtin function range also works
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# but numpy has its own implementation of a similar function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# its usage is similar to the built one - range(start, stop, step)
np.arange(2, 21, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
# there are also numerous ways of creating arrays with a given shape and values like 1s or 0s
# ones
display(np.ones(5))
display(np.ones((5,5)))

# zeros
display(np.zeros(5))
display(np.zeros((3,1)))

array([1., 1., 1., 1., 1.])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([0., 0., 0., 0., 0.])

array([[0.],
       [0.],
       [0.]])

In [14]:
# when we need an array with numbers evenly distributet between two given numerical values
# we can use a linspace function - linspace(start, stop, number of elements)
np.linspace(1,10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [15]:
# an example of printing out the docstring of a given function/method
print(np.linspace.__doc__)


    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True

In [16]:
# NumPy arrays can be reshaped using methods such as `reshape`, which, when combined with various initialization methods,
# offers additional possibilities—but here we must keep in mind the symmetry of the target array (the number of elements
# in the target array must equal the number of elements in the source array)
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# np.diag returns a two-dimensional square array of size (v x v) + abs(k), where v is the value of the first argument passed in
# the call to this function, which is an iterable object containing the elements to be placed on the diagonal
# of this matrix. If the second argument of this function, k (optional), is not specified or has a value of 0, then the elements 
# will be placed on the main diagonal; otherwise, the elements will be placed on the kth or -kth diagonal
# away from the main diagonal
np.diag((1,2,3,4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
np.diag(np.arange(5), 1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0]])

In [19]:
np.diag(np.arange(5), -1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0]])

In [20]:
# np.diag has also another usage - it can extract data from a diagonal within an existing array
arr = np.arange(1, 17).reshape((4,4))
print(arr)
print(np.diag(arr))
print(np.diag(arr, -1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]
[ 5 10 15]


## 2.2 Selected propertion of a numpy array

In [21]:
# informacje o liczbie elementów, liczbie wymiarów oraz o wielkościach każdego wymiaru
# number of elements, number of dimensions and shape (a tuple with number of elements in each dimension)
arr.size, arr.ndim, arr.shape

(16, 2, (4, 4))

In [22]:
# shape for a matrix (rows, cols)
arr = np.zeros((4,3))
display(arr)
arr.shape

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

(4, 3)

In [23]:
# with more dimensions reading and navigating becomes more difficult
arr = np.ones((3,3,3))
arr

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
!pip install matplotlib

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detai

In [25]:
# an example inspired on: https://matplotlib.org/stable/gallery/mplot3d/voxels.html#sphx-glr-gallery-mplot3d-voxels-py

import matplotlib.pyplot as plt

# array of shape 3 x 3 x 3 initialization
# coordinates (x, z, y)
x = np.ones((3, 3, 3))

# On the right, we filter the array x using the condition < 3, which returns
# an array of the same dimensions, where values that satisfy the condition are
# stored as the boolean value True, and those that do not satisfy it are stored as False
# although there are several ways to perform this conversion

cube1 = (x < 3)

# printing data of an array
display(cube1)

# you can test multiple examples - one at a time
# cube1[:,:,1] = False
# cube1[1,:,:] = False
cube1[:,1,:] = False
print(cube1)

colors = np.empty(cube1.shape, dtype=object)
colors[cube1] = 'green'

ax = plt.figure().add_subplot(projection='3d')
ax.axes.set_xlim3d(left=0, right=5) 
ax.axes.set_ylim3d(bottom=0, top=5) 
ax.axes.set_zlim3d(bottom=0, top=5) 
ax.voxels(cube1, facecolors=colors, edgecolor='k')


plt.xlabel('x')
plt.ylabel('y')
plt.show()

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

[[[ True  True  True]
  [False False False]
  [ True  True  True]]

 [[ True  True  True]
  [False False False]
  [ True  True  True]]

 [[ True  True  True]
  [False False False]
  [ True  True  True]]]


/tmp/ipykernel_13683/2181514878.py:37: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [26]:
# data type of an array (homogeneous for the whole array)
arr.dtype

dtype('float64')

In [27]:
# NumPy offers many data types that can be thought of as containers for information in NumPy arrays.
# These types do not correspond exactly to the types we know from the standard Python library, since “under the hood”
# we still have a C implementation.
# I will present a few examples here, but the number of available types is extensive, so
# I refer you to the documentation for a complete reference.

# As you have likely already noticed, a data type is assigned to an array automatically if we do not specify it 
# during its initialization. However, this will not always be optimal in terms of memory utilization for
# the data in that array.

def print_details(np_arr):
    print(np_arr, np_arr.dtype, np_arr.itemsize, np_arr.nbytes)

# we can define data type during array creation
arr_int = np.arange(1, 11, dtype='i') # int32 or int64 in most cases
arr_int2 = np.arange(1, 11, dtype='i4') # np.int32
arr_int3 = np.arange(1, 11, dtype='i1') # np.int8
arr_int4 = np.arange(1, 11, dtype='i2') # np.int16
arr_int5 = np.arange(1, 11, dtype='i8') # np.int64

print_details(arr_int)
print_details(arr_int2)
print_details(arr_int3)
print_details(arr_int4)
print_details(arr_int5)

[ 1  2  3  4  5  6  7  8  9 10] int32 4 40
[ 1  2  3  4  5  6  7  8  9 10] int32 4 40
[ 1  2  3  4  5  6  7  8  9 10] int8 1 10
[ 1  2  3  4  5  6  7  8  9 10] int16 2 20
[ 1  2  3  4  5  6  7  8  9 10] int64 8 80


In [28]:
# Each of these types also has an unsigned counterpart—that is, unlike the examples in the previous listing,
# integers are stored as unsigned, which doubles the range of decimal values that can be assigned to such a variable

arr_uint1 = np.arange(1, 11, dtype='u4') # lub np.int32
arr_uint2 = np.arange(1, 11, dtype='u8') # lub np.int64

print_details(arr_uint1)
print_details(arr_uint2)

[ 1  2  3  4  5  6  7  8  9 10] uint32 4 40
[ 1  2  3  4  5  6  7  8  9 10] uint64 8 80


In [29]:
# floating-point types
# float - f8 - 8 bytes (same as float64)
# float16 - f2 - 2 bytes
# float32 - f - 4 bytes
# float64 - d - 8 bytes

arr_1 = np.arange(1, 11, dtype='float16')
arr_2 = np.arange(1, 11, dtype='float32')
arr_3 = np.arange(1, 11, dtype='float64')

print_details(arr_1)
print_details(arr_2)
print_details(arr_3)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] float16 2 20
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] float32 4 40
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] float64 8 80


In [30]:
# other data types

# bool
bool_arr = np.arange(1, 11, dtype='b')
# string - unicode
unknown_arr = np.array(['Ala', 'ma', 'kota'])
unknown_arr2 = np.array(list('What could it be?'))


print_details(bool_arr)
print_details(unknown_arr)
print_details(unknown_arr2)

[ 1  2  3  4  5  6  7  8  9 10] int8 1 10
['Ala' 'ma' 'kota'] <U4 16 48
['W' 'h' 'a' 't' ' ' 'c' 'o' 'u' 'l' 'd' ' ' 'i' 't' ' ' 'b' 'e' '?'] <U1 4 68


## 2.3 Examples with selected operations on numpy array

### 2.3.1 Changing data type of an array

In [31]:
# we can try to change the type with astype function
arr =  np.arange(100_000, 8_000_000, 100_000)
print(arr)
print(arr.dtype)
print(arr.astype(np.uint32))
print(arr.astype(np.uint16))
print(arr.astype(np.uint8))

[ 100000  200000  300000  400000  500000  600000  700000  800000  900000
 1000000 1100000 1200000 1300000 1400000 1500000 1600000 1700000 1800000
 1900000 2000000 2100000 2200000 2300000 2400000 2500000 2600000 2700000
 2800000 2900000 3000000 3100000 3200000 3300000 3400000 3500000 3600000
 3700000 3800000 3900000 4000000 4100000 4200000 4300000 4400000 4500000
 4600000 4700000 4800000 4900000 5000000 5100000 5200000 5300000 5400000
 5500000 5600000 5700000 5800000 5900000 6000000 6100000 6200000 6300000
 6400000 6500000 6600000 6700000 6800000 6900000 7000000 7100000 7200000
 7300000 7400000 7500000 7600000 7700000 7800000 7900000]
int64
[ 100000  200000  300000  400000  500000  600000  700000  800000  900000
 1000000 1100000 1200000 1300000 1400000 1500000 1600000 1700000 1800000
 1900000 2000000 2100000 2200000 2300000 2400000 2500000 2600000 2700000
 2800000 2900000 3000000 3100000 3200000 3300000 3400000 3500000 3600000
 3700000 3800000 3900000 4000000 4100000 4200000 4300000 440

In [32]:
# print(chr(0x1F4A5) * 5)

&#x1F4A5; &#x1F4A5; &#x1F4A5; &#x1F4A5; &#x1F4A5;

In [33]:
# Let's try to explain this. We'll consider the first 5 values in the array
# do you know what happened in the code example above?

vals = list(arr[:5])

for val in vals:
    print(f'Oryginal: {val}, binary: {bin(val)},\
    bin 16: {bin(val)[:-17:-1][::-1]} , decimal {int(bin(val)[:-17:-1][::-1], base=2)}\
    bin 8: {bin(val)[:-9:-1][::-1]} , decimal {int(bin(val)[:-9:-1][::-1], base=2)}')

Oryginal: 100000, binary: 0b11000011010100000,    bin 16: 1000011010100000 , decimal 34464    bin 8: 10100000 , decimal 160
Oryginal: 200000, binary: 0b110000110101000000,    bin 16: 0000110101000000 , decimal 3392    bin 8: 01000000 , decimal 64
Oryginal: 300000, binary: 0b1001001001111100000,    bin 16: 1001001111100000 , decimal 37856    bin 8: 11100000 , decimal 224
Oryginal: 400000, binary: 0b1100001101010000000,    bin 16: 0001101010000000 , decimal 6784    bin 8: 10000000 , decimal 128
Oryginal: 500000, binary: 0b1111010000100100000,    bin 16: 1010000100100000 , decimal 41248    bin 8: 00100000 , decimal 32


> **WARNING!** Data conversion may result in a loss of precision! You should first analyze the data you intend to convert.

### 2.3.2 Numpy broadcasting

Let's consider an example of running a function on each element of an ordinary Python list.

In [34]:
my_list = list(range(1, 11))
print(my_list)

for idx in range(len(my_list)):
    my_list[idx] = my_list[idx] * 2

print(my_list)

# or in a more Pythonic way

my_list = [elem * 2 for elem in my_list]
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


[4, 8, 12, 16, 20, 24, 28, 32, 36, 40]

In [35]:
# numpy works in a different manner

arr = np.arange(1,11)
print(arr)
print(arr * 2)
# The operation is performed element-wise, i.e., on each element of the array
# or, in other words, it is broadcasted to each element of the array

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [36]:
# Most functions in the NumPy library also accept an array as an input argument
# and perform an operation on each of its elements
# Below, we will calculate the square root of each value in the array
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

### 2.3.3 Indexing and slicing

In [37]:
# indexing on a numpy array works in the same way as other index based collections
arr = np.arange(1, 11)
print(arr[0])

print(arr[-1])

print(arr[:5])

1
10
[1 2 3 4 5]


In [38]:
# slicing a multidimensional arrays is similar, but we need to provide an index or slice for each dimension

arr = np.arange(1, 17).reshape((4,4))
print(arr)

print(arr[0,0])
print(arr[:,0]) # all "rows", first "column"
print(arr[0,:]) # first "row"
print(arr[0:2,0:2]) # a 2x2 array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1
[ 1  5  9 13]
[1 2 3 4]
[[1 2]
 [5 6]]


In [39]:
# we can also assign a value to a slice from an array

arr[:,0] = 0
arr

array([[ 0,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 0, 10, 11, 12],
       [ 0, 14, 15, 16]])

If we now recall the example of an array that was subsequently displayed in a graph,
we were dealing with a **boolean array**, which is also called a **boolean map**.
This name refers to the operations that can be performed on other arrays using such arrays.
Such a map allows you to extract, assign, or apply a function to every value in the array
to which we "apply" the map—that is, the map will perform the operation on every
logical True value in the array and skip the operation for every False value. Examples follow.

In [40]:
arr = np.arange(1, 17).reshape((4,4))
print(arr)

# simple condition - returns a map where the key has the same dimensions and takes the value True wherever the condition is met
print((arr < 10))

# now we apply a map to an original array
print(arr[(arr < 10)])

# this works like a filter
# other examples will be presented on our future lectures

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]
 [False False False False]]
[1 2 3 4 5 6 7 8 9]


## 2.4 Examples on how to compare computation time

We already know that familiarity with the NumPy library is necessary to work efficiently with the Pandas library, which is extremely popular in the context of data analysis. Another important aspect is the processing speed offered by NumPy, especially when compared to Python’s standard library and equivalent calculations. 

Below are several examples comparing the performance of various Python code snippets using the `timeit` library.

In [41]:
from timeit import timeit


setup= """
import numpy as np
"""

setup_2 = """
from array import array
"""

stmt1 = """list(range(1, 100001))"""
stmt2 = """np.arange(1, 100001)"""
stmt3 = """array('I', range(1, 100001))"""

timeit(stmt=stmt1, number=1000), timeit(stmt=stmt2, setup=setup, number=1000), timeit(stmt=stmt3, setup=setup_2, number=1000)

(3.867632188999778, 0.03364525200004209, 3.2111740049999753)

As shown above, you can see the difference in speed between standard lists and a NumPy array in this specific case, where we create an array of 100,000 integer values. The entire process is repeated 1,000 times to average out the results.

## Exercises to complete on your own


**Task 1**  
Create and display an array consisting of 10 consecutive integer values in the range [1,10].






In [42]:
import numpy as np

# Task 1: integers from 1 to 10 in one array
# np.arange stops before the end number, so we use 11 to include 10.
ones_to_ten = np.arange(1, 11)
print(ones_to_ten)



[ 1  2  3  4  5  6  7  8  9 10]


**Task 2**   
Change the data type of the array from Task 1 to float32. Display this array.





In [43]:
import numpy as np

# Task 2: same numbers as Task 1, stored as float32
arr = np.arange(1, 11)
arr_float = arr.astype(np.float32)
print(arr_float)
print("dtype is:", arr_float.dtype)



[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
dtype is: float32


**Task 3**  
Create an array containing the consecutive powers of 2 for exponents from 2 to 16.





In [44]:
import numpy as np

# Task 3: powers of 2 for exponents 2 through 16 (inclusive)
# Build the list in a loop, then turn it into an array.
values = []
for exponent in range(2, 17):
    values.append(2**exponent)
powers = np.array(values)
print(powers)



[    4     8    16    32    64   128   256   512  1024  2048  4096  8192
 16384 32768 65536]


**Task 4**  
Create a 5x5 NumPy array with consecutive integer values from 1 to 25, and then display:
* the last value in the array (this is the value at the last row and column indices)
* the second column,
* the third row,
* the main diagonal,
* an array containing the values 9, 10, 14, and 15 (the array is 2x2)





In [45]:
import numpy as np

# Task 4: 5x5 grid with 1..25
grid = np.arange(1, 26).reshape(5, 5)
print("Full grid:")
print(grid)

# Last element: row index 4, column index 4 (Python starts at 0)
print("Last value:", grid[4, 4])

# Second column has index 1
print("Second column:", grid[:, 1])

# Third row has index 2
print("Third row:", grid[2, :])

# Main diagonal: same row and column index
diag_values = []
for i in range(5):
    diag_values.append(grid[i, i])
print("Main diagonal:", np.array(diag_values))

# 2x2 block with 9, 10, 14, 15 -> rows 1-2, cols 1-2
small = grid[1:3, 1:3]
print("2x2 block:", small)



Full grid:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Last value: 25
Second column: [ 2  7 12 17 22]
Third row: [11 12 13 14 15]
Main diagonal: [ 1  7 13 19 25]
2x2 block: [[ 7  8]
 [12 13]]


**Task 5**  
Based on the examples above and the graph from section 2.2, display the same array (3 x 3) in the following forms:
* only the elements for coordinates y = 1 are visible (x is the horizontal axis, y is the vertical axis, z is the “depth”)
* only values for z = 1 and z = 3 are visible, along with all values of x and y (this is like the first and last columns of this 3 x 3 x 3 cube)





In [46]:
import numpy as np
import matplotlib.pyplot as plt

# Task 5: 3x3x3 cube of ones, then show two voxel views like in the lab
cube = np.ones((3, 3, 3))

# View A: only the middle "y" slice (index 1) is visible
mask_y = np.zeros((3, 3, 3), dtype=bool)
for x in range(3):
    for z in range(3):
        mask_y[x, 1, z] = True
colors_y = np.empty(mask_y.shape, dtype=object)
colors_y[mask_y] = "green"
fig1, ax1 = plt.subplots(figsize=(6, 6), subplot_kw={"projection": "3d"})
ax1.voxels(mask_y, facecolors=colors_y, edgecolor="k")
ax1.set_title("Only y = 1")
plt.show()

# View B: first and last depth slice (z index 0 and 2 -> "1" and "3" in 1-based wording)
mask_z = np.zeros((3, 3, 3), dtype=bool)
for x in range(3):
    for y in range(3):
        mask_z[x, y, 0] = True
        mask_z[x, y, 2] = True
colors_z = np.empty(mask_z.shape, dtype=object)
colors_z[mask_z] = "steelblue"
fig2, ax2 = plt.subplots(figsize=(6, 6), subplot_kw={"projection": "3d"})
ax2.voxels(mask_z, facecolors=colors_z, edgecolor="k")
ax2.set_title("z planes 1 and 3 (0-based indices 0 and 2)")
plt.show()



/tmp/ipykernel_13683/2404821912.py:17: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/tmp/ipykernel_13683/2404821912.py:30: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


**Task 6**  
Based on the example from subsection 2.3.2, prepare a runtime test for the following three cases:
* Initialize a list of 10,000 integer values and multiply each element by 2 using a for loop
* As above, but using list comprehension (as a reminder: [expression for elem in collection])
* For a NumPy array



In [47]:
import numpy as np
from timeit import timeit

# Task 6: compare speed of doubling 10,000 integers three ways
n_numbers = 10000
repeats = 100  # how many times each approach is timed (keep reasonable in class)

# 1) plain list + for-loop
setup_loop = ""
stmt_loop = '''
nums = list(range(1, 10001))
doubled = []
for x in nums:
    doubled.append(x * 2)
'''

# 2) list comprehension
stmt_comp = '''
nums = list(range(1, 10001))
doubled = [x * 2 for x in nums]
'''

# 3) NumPy array
setup_np = "import numpy as np"
stmt_np = '''
arr = np.arange(1, 10001)
doubled = arr * 2
'''

t_loop = timeit(stmt_loop, setup=setup_loop, number=repeats)
t_comp = timeit(stmt_comp, setup=setup_loop, number=repeats)
t_np = timeit(stmt_np, setup=setup_np, number=repeats)

print("For-loop total seconds ({} runs): {:.4f}".format(repeats, t_loop))
print("List comprehension total seconds: {:.4f}".format(t_comp))
print("NumPy total seconds: {:.4f}".format(t_np))



For-loop total seconds (100 runs): 0.0575
List comprehension total seconds: 0.0564
NumPy total seconds: 0.0015
